### PR TITLE
README: Update supported version section [ci skip]

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR only updates the Ruby versions README section to include what's in the Travis matrix.

### CODE REVIEW

**Comment by janko-m** [comment]
Great, thanks!

**Comment by olleolleolle** [comment]
Hehe, well, Rubinius is no longer _in_ the matrix.

**Comment by olleolleolle** [comment]
Perhaps using the names which work for this project, you can add it back?

https://travis-ci.org/rubinius/travis-canary

**Comment by janko-m** [comment]
@olleolleolle I removed it in the past because it would often fail to even install, and as a mini-protest to the current maintainer. But I'm definitely open to adding it back if it would have stable installs.

**Comment by olleolleolle** [comment]
@janko-m If you're not keen on adding it to the CI matrix, I'd like to see it gone from the "supported versions" list. That would mean: It _could_ work, but there's no on-going effort to keep it working.

**Comment by janko-m** [comment]
Done

**Pull request merged**
